//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bajar_producto
    {
        public int id_bajar_producto { get; set; }
        public int id_detalle_producto { get; set; }
        public int cantidad { get; set; }
        public int id_usuario { get; set; }
        public int id_motivo { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha { get; set; }
    
        public virtual detalle_producto detalle_producto { get; set; }
        public virtual motivo motivo { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
