//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public compra()
        {
            this.detalle_compra = new HashSet<detalle_compra>();
            this.detalle_producto = new HashSet<detalle_producto>();
        }
    
        public int id_compra { get; set; }
        public int id_proveedor { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string num_fact { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int id_estado { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_compra> detalle_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_producto> detalle_producto { get; set; }
    }
}
