//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_compra()
        {
            this.detalle_producto = new HashSet<detalle_producto>();
        }
    
        public int id_detalle_compra { get; set; }
        public int id_compra { get; set; }
        public int id_producto { get; set; }
        public int cantidad_cajas { get; set; }
        public decimal precio_compra { get; set; }
        public int undxcajas { get; set; }
        public decimal total_und { get; set; }
        public Nullable<bool> enexposicion { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public int id_lote { get; set; }
        public bool estado { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual lote lote { get; set; }
        public virtual producto producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_producto> detalle_producto { get; set; }
    }
}
