//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_devolucion
    {
        public int id_detalledevolucion { get; set; }
        public int id_devolucion { get; set; }
        public int id_detalle_producto { get; set; }
        public Nullable<decimal> cantidad_cajas { get; set; }
        public Nullable<decimal> precio_cajas { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual detalle_producto detalle_producto { get; set; }
        public virtual devolucion devolucion { get; set; }
    }
}
