//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_producto()
        {
            this.bajar_producto = new HashSet<bajar_producto>();
            this.detalle_devolucion = new HashSet<detalle_devolucion>();
        }
    
        public int id_detalle_producto { get; set; }
        public int id_producto { get; set; }
        public int id_detalle_compra { get; set; }
        public int id_lote { get; set; }
        public decimal numero_caja { get; set; }
        public int undxcajas { get; set; }
        public Nullable<bool> enexposicion { get; set; }
        public Nullable<bool> estado { get; set; }
        public int id_compra { get; set; }
        public decimal iva { get; set; }
        public decimal precio_compra { get; set; }
        public decimal stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bajar_producto> bajar_producto { get; set; }
        public virtual compra compra { get; set; }
        public virtual detalle_compra detalle_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_devolucion> detalle_devolucion { get; set; }
        public virtual lote lote { get; set; }
        public virtual producto producto { get; set; }
    }
}
