//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public devolucion()
        {
            this.detalle_devolucion = new HashSet<detalle_devolucion>();
        }
    
        public int id_devolucion { get; set; }
        public int id_proveedor { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> total { get; set; }
        public int id_usuario { get; set; }
        public int id_tipo_devolucion { get; set; }
        public string num_devolucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_devolucion> detalle_devolucion { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual tipo_devolucion tipo_devolucion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
