//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class patologia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patologia()
        {
            this.producto_patologia = new HashSet<producto_patologia>();
        }

        public int id_patologia { get; set; }

        [MaxLength(30, ErrorMessage = "Maximo de carateres 30")]
        [MinLength(2, ErrorMessage = "Minimo de carateres 2")]
        [DisplayName("Patologia")]
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string nombre_patologia { get; set; }

        [MaxLength(50, ErrorMessage = "Maximo de carateres 50")]
        [DisplayName("Descripcion")]
        public string descripcion_patologia { get; set; }
        public bool estado { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_patologia> producto_patologia { get; set; }
    }
}
