//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.detalle_compra = new HashSet<detalle_compra>();
            this.detalle_producto = new HashSet<detalle_producto>();
            this.detalle_venta = new HashSet<detalle_venta>();
            this.producto_categoria = new HashSet<producto_categoria>();
            this.producto_patologia = new HashSet<producto_patologia>();
        }

        public int id_producto { get; set; }

        [MaxLength(30, ErrorMessage = "Maximo de carateres 30")]
        [MinLength(2, ErrorMessage = "Minimo de carateres 2")]
        [DisplayName("Producto")]
        [Required(ErrorMessage = "El campo es obligatorio")]

        public string nombre_producto { get; set; }

        [MaxLength(13, ErrorMessage = "Minimo de carateres 13")]
        [MinLength(12, ErrorMessage = "Minimo de carateres 12")]
        [DisplayName("Codigo")]
        [Required(ErrorMessage = "El campo es obligatorio")]

        public string codigo_producto { get; set; }

        [MaxLength(100, ErrorMessage = "Maximo de carateres 100")]
        [DisplayName("Descripcion")]

        public string descripcion_producto { get; set; }

        [DisplayName("Precio Venta")]
        [Required(ErrorMessage = "El campo es obligatorio")]

        
        public decimal precio_venta { get; set; }

        [DisplayName("Stock")]

        public int stock { get; set; }

        [DisplayName("Contiene")]
        [Required(ErrorMessage = "El campo es obligatorio")]

        public decimal contiene { get; set; }

        [DisplayName("UndxCajas")]
        [Required(ErrorMessage = "El campo es obligatorio")]

        public int undxcajas { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]

        public int id_umedida { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]

        public Nullable<int> id_generico { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]

        public int id_presentacion { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]

        public int id_laboratorio { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [DisplayName("Estado")]

        public bool estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_compra> detalle_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_producto> detalle_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
        public virtual generico generico { get; set; }
        public virtual laboratorio laboratorio { get; set; }
        public virtual presentacion presentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_categoria> producto_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_patologia> producto_patologia { get; set; }
        public virtual umedida umedida { get; set; }
    }
}
