//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.bajar_producto = new HashSet<bajar_producto>();
            this.compra = new HashSet<compra>();
            this.devolucion = new HashSet<devolucion>();
            this.venta = new HashSet<venta>();
        }

        public int id_usuario { get; set; }

        [MaxLength(25, ErrorMessage = "Maximo de carateres 25")]
        [MinLength(3, ErrorMessage = "Minimo de carateres 3")]
        [DisplayName("Nombre")]
        [Required(ErrorMessage = "El campo es obligatorio")]

        public string nombre_user { get; set; }

        [MaxLength(30, ErrorMessage = "Maximo de carateres 30")]
        [MinLength(3, ErrorMessage = "Minimo de carateres 3")]
        [DisplayName("Apellido")]
        [Required(ErrorMessage = "El campo es obligatorio")]

        public string apellido_user { get; set; }

        [MaxLength(30, ErrorMessage = "Maximo de carateres 30")]
        [MinLength(5, ErrorMessage = "Minimo de carateres 5")]
        [DisplayName("Correo")]
        [EmailAddress(ErrorMessage = "Escriba un correo valido")]
        [Required(ErrorMessage = "El campo es obligatorio")]

        public string email { get; set; }

        [DisplayName("Contraseña")]
        [MaxLength(100, ErrorMessage = "Maximo de carateres 100")]
        [MinLength(6, ErrorMessage = "Minimo de carateres 6")]

        public string contrasena { get; set; }

        [DisplayName("Estado")]

        public bool estado { get; set; }

        [DisplayName("Imagen")]

        public string imagen { get; set; }

        public int id_rol { get; set; }

        [DisplayName("cedula")]
        [MaxLength(14, ErrorMessage = "Maximo de carateres 14")]
        [MinLength(14, ErrorMessage = "Minimo de carateres 14")]
        [Required(ErrorMessage = "El campo es obligatorio")]

        public string usuario_cedula { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bajar_producto> bajar_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<devolucion> devolucion { get; set; }
        public virtual rol rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> venta { get; set; }
    }
}
