//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vista_productos_a_vencerse
    {
        public int id_detalle_producto { get; set; }
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string codigo_producto { get; set; }
        public decimal numero_caja { get; set; }
        public int undxcajas { get; set; }
        public bool enexposicion { get; set; }
        public bool estado { get; set; }
        public decimal stock { get; set; }
        public decimal precio_compra { get; set; }
        public decimal precio_venta { get; set; }
        public int undCajaProd { get; set; }
        public string nombre_presentacion { get; set; }
        public string nombre_laboratorio { get; set; }
        public string nombre_umedida { get; set; }
        public decimal contiene { get; set; }
        public string nlote { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
    }
}
