//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vista_Compra_listado
    {
        public int id_compra { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha { get; set; }
        public string num_fact { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int id_estado { get; set; }
        public string nombre_user { get; set; }
        public string apellido_user { get; set; }
        public string nombre_proveedor { get; set; }
    }
}
