//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vista_producto
    {
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string codigo_producto { get; set; }
        public string descripcion_producto { get; set; }
        public decimal precio_venta { get; set; }
        public int stock { get; set; }
        public decimal contiene { get; set; }
        public int undxcajas { get; set; }
        public int id_umedida { get; set; }
        public Nullable<int> id_generico { get; set; }
        public int id_presentacion { get; set; }
        public int id_laboratorio { get; set; }
        public bool estado { get; set; }
        public string nombre_presentacion { get; set; }
        public string nombre_laboratorio { get; set; }
        public string nombre_umedida { get; set; }
        public string nombre_generico { get; set; }
        public string patologias { get; set; }
        public string categorias { get; set; }
    }
}
