//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vista_detalle_compra
    {
        public int id_detalle_compra { get; set; }
        public int id_compra { get; set; }
        public int id_producto { get; set; }
        public int cantidad_cajas { get; set; }
        public decimal precio_compra { get; set; }
        public int undxcajas { get; set; }
        public decimal total_und { get; set; }
        public Nullable<bool> enexposicion { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public int id_lote { get; set; }
        public bool estado { get; set; }
        public string nombre_producto { get; set; }
        public string codigo_producto { get; set; }
        public string descripcion_producto { get; set; }
        public decimal contiene { get; set; }
        public string laboratorio { get; set; }
        public string presentacion { get; set; }
    }
}
