//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmalivio_Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vista_producto_patologia
    {
        public int id_productopatologia { get; set; }
        public int id_producto { get; set; }
        public int id_patologia { get; set; }
        public string nombre_patologia { get; set; }
        public bool estado { get; set; }
    }
}
